version: 0.2

env:
  variables:
    S3_BUCKET_NAME: your-bucket-name

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
      - echo Deployment completed!

artifacts:
  files:
    - '**/*'
  base-directory: dist
