version: 0.2

env:
  variables:
    S3_BUCKET_NAME: aws-cms-erp-frontend-app

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Checking files..."
      - ls -la
      - ls -la dist

      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://aws-cms-erp-frontend-app --delete --debug
